### ISSUE TITLE
Use buildah action

### ISSUE THREAD

**Issue by gbraad** [gbraad-fedora/fedora-workstation#1]
```yaml
name: Build OCI Image
on: [push]

env:
    IMAGE_NAME: ghcr.io/gbraad-fedora/fedora-bootc-workstation
    IMAGE_TAGS: latest ${{ github.sha }}
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Remove unwanted stuff
      uses: gbraad-devenv/remove-unwanted@v1

    - uses: actions/checkout@v4

    - name: Buildah Action
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        oci: true
        build-args: |
          BASE_IMAGE=quay.io/fedora/fedora-bootc
          BASE_VERSION=41
        containerfiles: |
          ./Containerfile
    - name: Push To GHCR
      uses: ./
      id: push
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        extra-args: |
          --disable-content-trust
```
